/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chandigarh.fantasy.champions.league;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
